### ISSUE TITLE
Incorrect symbol for lineComment

### ISSUE THREAD

**Issue by mirao** [luggage66/vscode-awk#1]
**Used SW:**
- AWK extension 0.0.1
- VSC 1.1.1 on Ubuntu 16.04

**Steps to reproduce:**
- click into a line
- toggle line comment

**Expected result:**
`# $1 = $2`

**Actual result:**
`// $1 = $2`

One more issue: blockComment should be disabled, because awk doesn't support it

So the item `comments` in config file `awk.configuration.json` should be:

```
"comments": {
                // symbol used for single line comment. Remove this entry if your language does not support line comments
        "lineComment": "#",
}
```

**Comment by luggage66** [comment]
Thanks for the info. Published.
